import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Shield, Activity, Radio, Server, Network, Target, TriangleAlert, BrainCircuit, Play, Square, ChevronRight, Search, Boxes, FileText, Settings, Wifi, LockKeyhole, Eye, CheckCircle2, Clock3, Zap, ArrowUpRight, Menu, X, SlidersHorizontal } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { api } from './services_api';
import { connectTelemetry } from './services_websocket';
import { adaptIncident, adaptAlert, adaptAsset, adaptTelemetry } from './adapters';
import './styles.css';

const stages = ['Reconnaissance','Initial Access','Execution','Persistence','Privilege Escalation','Lateral Movement','Command & Control','Exfiltration'];
function Badge({children,tone=''}) { return <span className={'badge '+String(tone).toLowerCase()}>{children}</span>; }
function Stat({icon:Icon,label,value,sub,tone=''}) { return <div className="stat"><div className="statIcon"><Icon size={17}/></div><div><div className="statLabel">{label}</div><div className={'statValue '+tone}>{value}</div><div className="statSub">{sub}</div></div></div>; }
function Panel({title,eyebrow,children,action}) { return <section className="panel"><div className="panelHead"><div><div className="eyebrow">{eyebrow}</div><h3>{title}</h3></div>{action}</div>{children}</section>; }

function AttackGraph({incident}) {
  const graph = incident?.graph || {nodes:[],edges:[]};
  const nodes = graph.nodes || [];
  const edges = graph.edges || [];
  if (!nodes.length) return <div className="graph"><div className="muted" style={{padding:24}}>Waiting for Person 3 attack-graph output…</div></div>;
  const pos = Object.fromEntries(nodes.map((n,i)=>[n.id,{x:12+(i%4)*25,y:25+Math.floor(i/4)*42}]));
  return <div className="graph"><svg viewBox="0 0 1000 420" preserveAspectRatio="none">
    <defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z"/></marker></defs>
    {edges.map((e,i)=>{const a=pos[e.source],b=pos[e.target]; if(!a||!b)return null; return <line key={i} className="edge active" x1={a.x*10} y1={a.y*4.2} x2={b.x*10} y2={b.y*4.2} markerEnd="url(#arrow)"/>})}
    {nodes.map((n,i)=>{const p=pos[n.id]; return <g key={n.id} transform={`translate(${p.x*10},${p.y*4.2})`}><circle className={'node '+(n.type==='asset'?'warn':'safe')} r="22"/><text className="nodeText" textAnchor="middle" dy="4">{String(n.id).slice(0,12)}</text></g>})}
  </svg><div className="graphLegend"><span><i className="dot warn"/>Asset</span><span><i className="dot safe"/>IP</span></div></div>;
}

function useDashboard() {
  const [state,setState] = useState({incidents:[],alerts:[],assets:[],health:null,topology:null,telemetry:[],ws:'disconnected',loading:true,error:null});
  const refresh = async () => {
    try {
      const [inc,alerts,assets,health,topology] = await Promise.all([api.incidents(),api.alerts(),api.assets(),api.health(),api.topology()]);
      setState(s=>({...s,incidents:(inc.incidents||[]).map(adaptIncident),alerts:(alerts.alerts||[]).map(adaptAlert),assets:(assets.assets||[]).map(adaptAsset),health,topology,loading:false,error:null}));
    } catch (error) { setState(s=>({...s,loading:false,error:error.message})); }
  };
  useEffect(()=>{ refresh(); const stop=connectTelemetry({onStatus:ws=>setState(s=>({...s,ws})),onEvent:packet=>setState(s=>({...s,telemetry:[adaptTelemetry(packet),...s.telemetry].slice(0,50)}))}); return stop;},[]);
  return {...state,refresh};
}

function CommandCentre({data}) {
  const [selectedId,setSelectedId]=useState(data.incidents[0]?.id);
  const [simulation,setSimulation]=useState(null);
  const [running,setRunning]=useState(false);
  const selected=data.incidents.find(x=>x.id===selectedId)||data.incidents[0];
  useEffect(()=>{if(!selectedId&&data.incidents[0])setSelectedId(data.incidents[0].id)},[data.incidents,selectedId]);
  const start=async()=>{try{const r=await api.startSimulation({duration_seconds:300,seed:42,enable_normal_traffic:true,attack_scenarios:['apt_campaign']});setSimulation(r);setRunning(true);}catch(e){alert(e.message)}};
  const stop=async()=>{if(simulation?.task_id)await api.stopSimulation(simulation.task_id);setRunning(false);};
  const health=data.health||{};
  const events=data.telemetry.length?data.telemetry:data.alerts.map(a=>adaptTelemetry(a));
  const risk=selected?.risk ?? 0;
  return <main><div className="pageTitle"><div><div className="eyebrow">OPERATIONS / COMMAND CENTRE</div><h1>Cyber Defense Command Centre</h1><p>Live outputs from Person 1 telemetry/pipeline and Person 3 correlation intelligence.</p></div><div className="controls"><button className={running?'danger':'primary'} onClick={running?stop:start}>{running?<><Square size={14}/> Stop simulation</>:<><Play size={14}/> Run simulation</>}</button></div></div>
  {data.error&&<div className="callout"><TriangleAlert size={15}/><span>Backend unavailable: {data.error}. Start FastAPI at localhost:8000.</span></div>}
  <div className="stats"><Stat icon={Shield} label="Network Risk" value={risk.toFixed(1)} sub={selected?.risk_level||'NO INCIDENT'} tone="risk"/><Stat icon={TriangleAlert} label="Active Incidents" value={String(data.incidents.length).padStart(2,'0')} sub={`${data.incidents.filter(x=>x.severity==='CRITICAL').length} critical`}/><Stat icon={Target} label="Affected Assets" value={new Set(data.incidents.flatMap(x=>x.assets)).size} sub="from correlation engine"/><Stat icon={BrainCircuit} label="Predicted Attacks" value={data.incidents.filter(x=>x.next).length} sub={`highest ${Math.max(0,...data.incidents.map(x=>x.confidence))}%`} tone="prediction"/><Stat icon={Activity} label="Events / min" value={health.normalizer?.events_normalized??'—'} sub={`WebSocket ${data.ws}`} /></div>
  <div className="gridMain"><Panel eyebrow="INCIDENT INTELLIGENCE" title={selected?`${selected.id} • ${selected.stage}`:'No incident'} action={selected&&<Badge tone={selected.severity}>{selected.severity}</Badge>}>
    {selected?<><div className="incidentTop"><div className="riskCircle"><strong>{selected.risk}</strong><span>RISK SCORE</span></div><div className="incidentSummary"><div className="miniGrid"><div><small>CONFIDENCE</small><b>{selected.confidence}%</b></div><div><small>NEXT STAGE</small><b>{selected.next}</b></div><div><small>ASSETS</small><b>{selected.assets.length}</b></div><div><small>TECHNIQUES</small><b>{selected.techniques.length}</b></div></div></div></div><AttackGraph incident={selected}/><div className="stageFlow">{stages.map((s,i)=><div className={'stage '+(s===selected.stage?'current':selected.chain.some(c=>c.stage===s)?'done':s===selected.next?'predicted':'')} key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</div>)}</div></>:<div className="muted">No incident intelligence is available yet.</div>}
  </Panel><div className="sideStack"><Panel eyebrow="PREDICTION ENGINE" title="Next attack prediction">{selected?<><div className="predictionHero"><BrainCircuit size={22}/><div><b>{selected.next}</b><span>Person 3 confidence</span></div><strong>{selected.confidence}%</strong></div>{Object.entries(selected.factors||{}).map(([k,v])=><div className="predRow" key={k}><span>{k.replaceAll('_',' ')}</span><b>{typeof v==='number'?v:''}</b><div className="meter"><i style={{width:`${Math.min(100,Number(v)||0)}%`}}/></div></div>)}<div className="callout"><Zap size={15}/><span>Prediction, risk factors and attack graph are read directly from the IncidentIntelligenceReport contract.</span></div></>:<div className="muted">No prediction available.</div>}</Panel>
  <Panel eyebrow="RESPONSE ADVISOR" title="AI recommended actions">{selected?.recommendations?.map((action,i)=><div className="response" key={action}><div className="responseIcon">{i+1}</div><div><b>{action}</b><span>Analyst approval required</span></div><button onClick={async()=>{try{const r=await api.simulateResponse({incident_id:selected.sourceId||selected.id,action});alert(`Simulation: risk ${r.before.risk_score} → ${r.after.risk_score}`)}catch(e){alert(e.message)}}}><ChevronRight size={17}/></button></div>)}<div className="humanLoop"><Eye size={15}/><span><b>Human-in-the-loop:</b> response endpoint is simulation-only.</span></div></Panel></div></div>
  <div className="gridBottom"><Panel eyebrow="LIVE TELEMETRY" title="Operational event stream" action={<Badge tone={data.ws==='connected'?'healthy':'warning'}><span className="liveDot"/> {data.ws.toUpperCase()}</Badge>}><div className="eventTable">{events.slice(0,8).map((e,i)=><div className="eventRow" key={e.eventId+i}><span className="mono muted">{new Date(e.timestamp).toLocaleTimeString()}</span><Badge tone={e.severity}>{e.threatType}</Badge><b className="mono">{e.asset}</b><span>{e.evidence||e.destinationIp||'Event received'}</span><ChevronRight size={14} className="muted"/></div>)}</div></Panel><Panel eyebrow="PIPELINE HEALTH" title="Telemetry processing"><div className="healthList">{[['Event Bus',health.event_bus],['OCSF Normalizer',health.normalizer],['Storage',health.store],['WebSocket',data.ws]].map(([name,value])=><div className="healthRow" key={name}><span className="healthLight"/><b>{name}</b><span>{typeof value==='string'?value:JSON.stringify(value||{})}</span><Badge tone="healthy">OPERATIONAL</Badge></div>)}</div></Panel></div>
  <div className="gridBottom"><Panel eyebrow="INCIDENT QUEUE" title="Prioritized investigations">{data.incidents.map(x=><button className={'incidentRow '+(selected?.id===x.id?'selected':'')} onClick={()=>setSelectedId(x.id)} key={x.id}><span className="incidentId">{x.id}</span><Badge tone={x.severity}>{x.severity}</Badge><span>{x.stage}</span><span className="muted">{x.assets.length} assets</span><strong>{x.risk}</strong><ChevronRight size={15}/></button>)}</Panel><Panel eyebrow="RAW ALERTS" title="Person 1 correlation inputs">{data.alerts.slice(0,5).map(a=><div className="healthRow" key={a.event_id}><b className="mono">{a.event_id}</b><span>{a.threat_type}</span><span>{a.asset_id}</span><Badge tone={a.severity}>{a.severity}</Badge></div>)}</Panel></div></main>;
}

function Assets({data}){return <main><div className="pageTitle"><div><div className="eyebrow">INFRASTRUCTURE / ASSET INVENTORY</div><h1>Military Network Assets</h1><p>{data.assets.length} assets from the simulator topology.</p></div></div><div className="assetGrid">{data.assets.map(a=><div className="assetCard" key={a.asset_id}><div className="assetCardTop"><div className={'assetStatus '+a.status}/><span className="mono">{a.hostname}</span><Badge tone={a.criticality}>{a.criticality}</Badge></div><h3>{a.hostname}</h3><p>{a.type}</p><div className="assetMeta"><span>{a.segment}</span><span className="mono">{a.ip}</span></div><div className="assetFooter"><span><Server size={14}/> {a.status}</span><span>{a.ports?.length||0} ports</span></div></div>)}</div></main>}
function NetworkPage({data}){return <main><div className="pageTitle"><div><div className="eyebrow">TOPOLOGY / NETWORK MAP</div><h1>Operational Network Map</h1><p>Live asset inventory mapped to the simulator's six network segments.</p></div></div><div className="networkMap"><div className="segmentList">{(data.topology?.segments||[]).map((s,i)=><div className="segment" key={s.id}><div className="segmentNo">0{i+1}</div><div><b>{s.label}</b><span>{data.assets.filter(a=>a.segment===s.id).length} assets</span></div></div>)}</div><div className="mapCanvas"><div className="mapGrid">{data.assets.map((a,i)=><div key={a.asset_id} className={'mapAsset '+a.status} style={{left:(8+(i%6)*15)+'%',top:(12+Math.floor(i/6)*18)+'%'}}><div>{a.hostname}</div><small>{a.segment}</small></div>)}</div><div className="mapCenter"><Shield size={30}/><b>CYBER RANGE</b><span>30+ simulated assets</span></div></div></div></main>}
function Incidents({data}){const [q,setQ]=useState('');const list=data.incidents.filter(x=>(x.id+x.stage+x.severity).toLowerCase().includes(q.toLowerCase()));return <main><div className="pageTitle"><div><div className="eyebrow">OPERATIONS / INCIDENTS</div><h1>Incident Command</h1><p>Person 3 intelligence reports.</p></div></div><div className="search wideSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search incidents..."/></div><div className="incidentList">{list.map(x=><div className="bigIncident" key={x.id}><div className="bigIncidentHead"><b>{x.id}</b><Badge tone={x.severity}>{x.severity}</Badge><span className="muted">{x.stage}</span><strong>{x.risk} risk</strong></div><div className="bigIncidentBody"><div><small>AFFECTED ASSETS</small><p>{x.assets.join(' • ')}</p></div><div><small>MITRE TECHNIQUES</small><p>{x.techniques.join(' • ')}</p></div><div><small>NEXT PREDICTION</small><p>{x.next} <Badge tone="prediction">{x.confidence}%</Badge></p></div></div></div>)}</div></main>}
function WhatIf({data}){const [selected,setSelected]=useState(data.incidents[0]);const [result,setResult]=useState(null);const [action,setAction]=useState('');return <main><div className="pageTitle"><div><div className="eyebrow">RESPONSE / DECISION LAB</div><h1>What-If Response Lab</h1><p>Simulation-only response analysis backed by the command-centre API.</p></div></div><div className="whatGrid"><Panel eyebrow="SCENARIO" title={selected?.id||'No incident'}><div className="scenario"><Badge tone={selected?.severity}>{selected?.severity}</Badge><h2>{selected?.stage}</h2><p>{selected?.assets?.join(' → ')}</p>{(selected?.recommendations||[]).map(x=><button className={action===x?'choice active':'choice'} key={x} onClick={async()=>{setAction(x);try{setResult(await api.simulateResponse({incident_id:selected.sourceId||selected.id,action:x}))}catch(e){alert(e.message)}}}><LockKeyhole size={17}/><span><b>{x}</b><small>Simulate only</small></span>{action===x?<CheckCircle2/>:<ChevronRight/>}</button>)}</div></Panel><Panel eyebrow="IMPACT ANALYSIS" title={result?'After simulated response':'Current state'}>{result?<><div className="compare"><div><small>RISK SCORE</small><strong>{result.after.risk_score}</strong><span>from {result.before.risk_score}</span></div><div><small>RISK REDUCTION</small><strong>{result.risk_reduction}</strong><span>points</span></div><div><small>NEXT-STAGE CONF.</small><strong>{Math.round(result.after.prediction_confidence*100)}%</strong><span>simulated</span></div></div><div className="whatGraph">SIMULATION ONLY • {result.action}</div></>:<div className="muted">Choose a recommended action to calculate the before/after risk.</div>}</Panel></div></main>}
function Reports({data}){return <main><div className="pageTitle"><div><div className="eyebrow">INTELLIGENCE / REPORTING</div><h1>Mission Reports</h1><p>Report-ready intelligence assembled from live API data.</p></div></div><div className="reportGrid">{data.incidents.map(x=><div className="reportCard" key={x.id}><FileText size={22}/><div><b>Incident Intelligence Report</b><span>{x.id} • {x.severity} • {x.risk} risk • {x.confidence}% prediction confidence</span></div><ArrowUpRight size={16}/></div>)}</div></main>}
function App(){const data=useDashboard();const [page,setPage]=useState('command');const [mobile,setMobile]=useState(false);const nav=[['command','Command Centre',Shield],['incidents','Incidents',TriangleAlert],['network','Network Map',Network],['assets','Asset Inventory',Boxes],['whatif','What-If Lab',SlidersHorizontal],['reports','Reports',FileText]];return <div className="app"><aside className={mobile?'open':''}><div className="brand"><div className="brandMark"><Shield size={20}/></div><div><b>CYBER DEFENSE</b><span>COMMAND CENTRE</span></div><button className="close" onClick={()=>setMobile(false)}><X size={18}/></button></div><div className="mission"><span>MISSION STATUS</span><b><i/> {data.ws==='connected'?'OPERATIONAL':'CONNECTING'}</b><small>LIVE BACKEND • OCSF 1.3.0</small></div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>{setPage(id);setMobile(false)}} key={id}><Icon size={17}/><span>{label}</span>{id==='incidents'&&<em>{data.incidents.length}</em>}</button>)}</nav><div className="sideBottom"><button><Radio size={16}/> Live Operations</button><button><Activity size={16}/> System Health</button><button><Settings size={16}/> Settings</button><div className="version">OCSF 1.3.0 • CYBER RANGE v1.0</div></div></aside><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb"><span>DEFENSE NETWORK</span><ChevronRight size={13}/><b>{nav.find(x=>x[0]===page)?.[1].toUpperCase()}</b></div><div className="topStatus"><span><Wifi size={14}/> WS {data.ws.toUpperCase()}</span><span><Clock3 size={14}/> {new Date().toLocaleTimeString()}</span><div className="avatar">A</div></div></header>{page==='command'?<CommandCentre data={data}/>:page==='assets'?<Assets data={data}/>:page==='network'?<NetworkPage data={data}/>:page==='whatif'?<WhatIf data={data}/>:page==='incidents'?<Incidents data={data}/>:<Reports data={data}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
